version: "2"
run:
  modules-download-mode: readonly
  tests: false
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - wrapperFunc
        - importShadow
        - unnamedResult
        - paramTypeCombine
        - emptyStringTest
        - nestingReduce
        - elseif
        - ifElseChain
        - whyNoLint
        - unnecessaryDefer
        - commentFormatting
        - commentedOutCode
        - emptyFallthrough
      enabled-tags:
        - diagnostic
        - performance
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G112
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errorlint
        text: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
