name: Bug Report
description: Report a bug in the project.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please provide as much detail as possible to help us understand and resolve the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: "Describe the bug in detail. Include steps to reproduce, expected behavior, and actual behavior."
      placeholder: |
        Describe the bug here. What is the bug?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "List the steps to reproduce the bug. This helps us reproduce and debug the issue."
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: "Provide a code example that reproduces the issue."
      placeholder: |
        ```go
        // Your code here
        ```
    validations:
      required: false

  - type: textarea
    id: error-log
    attributes:
      label: Error Log
      description: "Paste any relevant error logs here."
      placeholder: |
        Paste your error log here.
    validations:
      required: false

  - type: input
    id: release-version
    attributes:
      label: Release Version
      description: "Specify the release version."
      placeholder: |
        e.g., v1.0.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: "Specify the version of Go that you are using."
      placeholder: |
        e.g., Go 1.21
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: "Specify the operating system you are using."
      placeholder: |
        e.g., Windows 10, macOS 11.2.1, Ubuntu 20.04
    validations:
      required: true

  - type: input
    id: related-issue
    attributes:
      label: Related Issue
      description: "If this bug is related to a specific issue or pull request, provide a link or reference here. (Optional)"
      placeholder: |
        e.g., #123 or https://github.com/cyberstudio/jsonj/issues/123
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Add any additional information that might help us in resolving the bug."
      placeholder: |
        Any other relevant details.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        _Thank you for providing the details! Our team will review and address the bug as soon as possible._
