name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2
        only-new-issues: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Publish doc
      if: ${{ !env.ACT }}  # skip if run locally with ACT
      run: |
        export latest="$(git describe --tags `git rev-list --tags --max-count=1`)"
        curl https://proxy.golang.org/github.com/cyberstudio/jsonj/@v/$latest.info
